export const UPDATE_DEVICE_SHADOW = 'UPDATE_DEVICE_SHADOW';
export const RECEIVE_DEVICE_SHADOW_UPDATE =  'RECEIVE_DEVICE_SHADOW_UPDATE';
export const SET_CONNECTED_STATUS = 'SET_CONNECTED_STATUS';
export const SET_USER_INFO = 'SET_USER_INFO';
